name: DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks (Secrets Scan)
        uses: zricethezav/gitleaks-action@v2
        with:
          args: '--path=. --exit-code 1'

  build-and-scan:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          IMAGE: ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:latest
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull $IMAGE
            docker stop devsecops-flask || true
            docker rm devsecops-flask || true
            docker run -d -p 5000:5000 --name devsecops-flask $IMAGE
          EOF
